Feature: ContentType

  Scenario: Add content type and delete it
    Given I am authenticated as "nicolas"
    When I click on the element with css selector ".fa-desktop"
    And I click on the element with css selector "#nav-content_types"
    And I wait some second "5"
    And I click on the element with css selector ".bh-button-add"
    And I wait some second "3"
    Then I should see "Content type id"
    When I reload the page
    And I wait some second "3"
    And I should see "Content type id"
    Then I should be on "/admin/#content_types/add"
    When I fill in "content_type_names_0_value" with "test content type"
    And I click on the element with css selector ".prototype-add"
    And I wait some second "3"
    Then I should see "Field id"
    When I fill in "content_type_fields_0_fieldId" with "first field id"
    And I fill in "content_type_fields_0_labels_0_value" with "first field label"
    And I press "content_type_submit"
    And I wait some second "5"
    Then I should see "The content type has been created"
    When I click on the element with css selector ".back-to-list"
    And I wait some second "5"
    Then I should see "test_content_type"
    And I should be on "/admin/#content_types/list"
    When I click on the last element ".btn-danger"
    And I wait some second "2"
    Then I should see "Delete this element"
    When I press "bot2-Msg1"
    And I wait some second "2"
    Then I should not see "test_content_type"
    When I reload the page
    And I wait some second "3"
    Then I should not see "test_content_type"
